org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx3072M
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.parallel=true

# Proxy (sandbox egress)
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1|::1

kotlin.code.style=official
kotlin.daemon.useFallbackStrategy=false

android.useAndroidX=true
android.nonTransitiveRClass=true

# KMP / Compose
org.jetbrains.compose.experimental.jscanvas.enabled=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
