org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx3072M
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.parallel=true

kotlin.code.style=official
kotlin.daemon.useFallbackStrategy=false

android.useAndroidX=true
android.nonTransitiveRClass=true

# KMP / Compose
org.jetbrains.compose.experimental.jscanvas.enabled=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
